
// This file is auto-generated by vite-plugin-phaser-asset-pack
// Do not edit this file manually

export const RESOURCES = {
  "comet-1": "comet-1",
  "comet-2": "comet-2",
  "comet-3": "comet-3",
  "martin": "martin",
  "texture": "texture",
} as const;
