
// This file is auto-generated by vite-plugin-phaser-asset-pack
// Do not edit this file manually

export const RESOURCES = {
  "build-H2compressor": "build-H2compressor",
  "build-O2compressor": "build-O2compressor",
  "build-chemicalplant": "build-chemicalplant",
  "build-condenser": "build-condenser",
  "build-duster": "build-duster",
  "build-electrolysis": "build-electrolysis",
  "build-fuelcell": "build-fuelcell",
  "build-generator": "build-generator",
  "build-miner": "build-miner",
  "build-solarpanel": "build-solarpanel",
  "sfx-alert": "sfx-alert",
  "sfx-click": "sfx-click",
  "sfx-electricity": "sfx-electricity",
  "sfx-gas-burst": "sfx-gas-burst",
  "sfx-gui-clip": "sfx-gui-clip",
  "sfx-gui-confirm": "sfx-gui-confirm",
  "sfx-gui-deny": "sfx-gui-deny",
  "sfx-gui-window-opens": "sfx-gui-window-opens",
  "sfx-mine-stardust": "sfx-mine-stardust",
  "sfx-pick-up": "sfx-pick-up",
  "sfx-put-down": "sfx-put-down",
  "comet-1": "comet-1",
  "comet-2": "comet-2",
  "comet-3": "comet-3",
  "martin": "martin",
  "texture": "texture",
} as const;
