export const CREDITS = {
  "Victor Debone (javascripl)": [
    "Project lead",
    "Core gameplay",
    "Comet spin",
    "UI code",
    "Comet and planet models",
    "Resource mechanics",
    "Game logo",
    "Dynamic music",
    "Balancing",
    "Input handling",
    "Game intro and ending",
    "Scene manager",
    "Mining cursor",
    "Color palette",
    "Debug panel",
    "Panel styling",
    "Sprite slicing",
    "Texture packing",
    "State machines",
    "ThreeJS and Phaser integration",
    "Various bug fixing and polish",
  ],
  "Christer 'McFunkypants' Kaitila": [
    "Building models (generator, compression, condenser, fuel cell,",
    "solar panels, miner, electrolysis, chemical plant, duster)",
    "Sounds (various building sounds, interface sounds,",
    "mining, build interactions, rocket launch)",
    "UI icons",
    "Building materials",
    "Base audio implementation",
    "Mute toggle",
    "Placeholder music during development",
    "Asset bug fix",
  ],
  "Michael Fewkes": ["Music", "Rocket engine loop"],
  "Patrick McKeown": [
    "Button text readability improvement",
    "Mining pop up fade",
    "UI text outline",
    "Building hover tips",
    "Volume tracking",
  ],
  "Vaan Hope Khani": [
    "Pause support",
    "Title logo concept (draft, not in release)",
  ],
  "Jason Timms": ["Bug fixing (pause issue, minor animation error)"],
  "Randy 'oneseedfruit' Tan Shaoxian": ["WASD view controls", "Bug fixing"],
  Testing: [
    "Michael Avrie (HomeTeam)",
    "Klaim (HomeTeam)",
    "Luis Montaña (HomeTeam)",
    "kepysic (external)",
    "Michał Gniadek (external)",
    "Anonymous testers",
  ],
  "And open source libraries": [
    "Phaser",
    "ThreeJS",
    "Tweakpane",
    "vite",
    "jsdom",
    "maxrects-packer",
    "sharp",
    "terser",
    "ts-node",
    "typescript",
    "vitest",
    "yargs",
  ],
};
